### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by lukashaider** [m4thieulavoie/sass-to-string#119]
I tried to use sass-to-string using the webpack loader, but had an encoding problem.

In my scss file there was something like this:
```
$icon: unquote("\"\\") + unquote("f101\"");

#example {
    content: $icon;
}
```

As a result I got:
![image](https://user-images.githubusercontent.com/13654851/114954549-2252db00-9e5b-11eb-9176-46f99de89d3f.png)

instead of:
![image](https://user-images.githubusercontent.com/13654851/114954648-562e0080-9e5b-11eb-92d3-c13195df55e4.png)

**Comment by m4thieulavoie** [comment]
Thanks for filing an issue! I'll try to reproduce locally and attempt a fix as soon as I have a couple of hours!

**Comment by m4thieulavoie** [comment]
@lukashaider I did manage to reproduce. However, I'm not clear on why you have to have two different `unquote` statements, can you elaborate on that?
I got to confirm that `sass-to-string` handles properly the following
```scss
$icon: unquote('"\f101"');
```

Waiting for your feedback to continue further investigation

**Comment by m4thieulavoie** [comment]
So after further investigation, I managed to find that `sass-loader` does not handle really well such a scenario.

I updated [this line](https://github.com/webpack-contrib/sass-loader/blob/master/test/scss/language.scss#L6)

to 
```scss
$pi:            unquote("\"\\") + unquote("e0C6\"");
```

and got the following error running unit tests:

![image](https://user-images.githubusercontent.com/44816587/115130149-02d2c400-9fbb-11eb-8bc1-842687603a14.png)

**Comment by lukashaider** [comment]
Hey, thank you for reproducing the error! I stumbled onto the problem because I tried to use AGGrid, and they use it like this for their Icons:
[https://github.com/ag-grid/ag-grid/blob/master/dist/styles/ag-theme-balham/sass/_ag-theme-balham-font-vars.scss](url)

That lead to some problems not loading the styling correctly for me.

**Comment by m4thieulavoie** [comment]
Gotcha, thanks for the context. I think the best would be to forward this issue in `sass-loader` since the encoding issue seems to be on their end 👍

**Comment by lukashaider** [comment]
Hm okay. I thought it had to be this. I managed to make it work using sass-loader and then css-loader with .toString();

**Comment by m4thieulavoie** [comment]
> Hm okay. I thought it had to be this. I managed to make it work using sass-loader and then css-loader with .toString();

Would you happen to have a branch I can checkout to look into it?
