### ISSUE TITLE
Bad escape sequence when including bootstrap

### ISSUE THREAD

**Issue by Tim-Erwin** [m4thieulavoie/sass-to-string#259]
Thank you for this plugin, exactly what I need for my web component. My component is quite big so that I need to include the bootstrap CSS. That starts with

```
/*
 * Bootstrap v4.4.1 (https://getbootstrap.com/)
 * Copyright 2011-2019 The Bootstrap Authors
 * Copyright 2011-2019 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
```

However, I get the following error message: 

    ERROR in ./src/styles.scss 2:24
    Module parse failed: Bad escape sequence in untagged template literal (2:24)
    File was processed with these loaders:
     * ./node_modules/sass-to-string/lib/index.js
     * ./node_modules/postcss-loader/src/index.js
     * ./node_modules/sass-loader/lib/loader.js
    You may need an additional loader to handle the result of these loaders.
    | 
    >         const styles = `/*
    |  * Bootstrap v4.4.1 (https://getbootstrap.com/)

I have been looking for a way to remove comments from (S)CSS automatically, didn't find any, removed the comment manually, got the next error with some other characters it didn't like which are not comments. I'm out of ideas how to fix that. Do you have any ideas what I could try?

**Comment by Tim-Erwin** [comment]
Ups, sorry for the title, somehow messed that up. Was supposed to be "Bad escape sequence when including bootstrap"

**Comment by m4thieulavoie** [comment]
Hey there, thanks for reaching out! 👋  I think sass-to-string should definitely handle this, but until a fix is released (I'll try to get on it ASAP, but feel free to give it a shot if you feel like it 💪 ), maybe one thing you could try is to minify the SCSS with a loader _prior_ running sass-to-string, but even then you'd probably still hit the same issue.

Will keep you posted!

**Comment by m4thieulavoie** [comment]
@Tim-Erwin `sass-to-string` has a very similar approach in its sandbox (`npm start`) where it simply loads up bootstrap CSS and appends it to the content of the page as you can see [here](https://github.com/m4thieulavoie/sass-to-string/blob/master/webpack.config.js#L23:L37). Can you maybe provide a repository I could checkout and have a look to help you out?

**Comment by Tim-Erwin** [comment]
@Tim-Erwin , thanks for your quick reply.

> one thing you could try is to minify the SCSS with a loader prior running sass-to-string
I tried that, but couldn't find a suitable loader. Maybe you can recommend one? Will look again.

> Can you maybe provide a repository I could checkout and have a look to help you out?
Should have done that earlier. Turns out, `sass-to-string` is not the problem, but the fact that I hade `node-sass` installed. A simple `npm uninstall --save node-sass` fixed the problem.

**Comment by m4thieulavoie** [comment]
Glad you got it sorted out @Tim-Erwin 😄
