### ISSUE TITLE
A way to use in Webpack Encore

### ISSUE THREAD

**Issue by kl3sk** [m4thieulavoie/sass-to-string#6]
I'll try to make it working inside Webpak Encore but I have this error:

`SassError: Invalid CSS after "": expected 1 selector or at-rule, was "const styles = ``;"`

I add this into `webpack.config.js`

```js
.addRule({
    test: /\.styles.scss$/,
    exclude: /node_modules/,
    use: [
        "sass-to-string",
            {
            loader: "sass-loader",
            options: {
                sassOptions: {
                    outputStyle: "compressed",
                },
            },
        },
    ],
})
```

Any help please

**Comment by m4thieulavoie** [comment]
Hey thanks for your issue, sorry I took so long to get to it. Are you still experiencing the issue? Can you share a repo exposing the issue?

**Comment by kl3sk** [comment]
Hello,

Sorry it is old now, I don't remember why I faced this issue. I maybe found an other solution.

I'll try to dig on it and come back.

Thx
